version: '3.8'

services:
  postgres:
    container_name: tp_container
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: name
      POSTGRES_PASSWORD: name
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: